name: nayef_common_domain_toolkit
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.2.6

dependencies:
  logging: ^1.2.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
