name: nayef_common_data_toolkit
description: "A new Flutter package project."
version: 1.0.3
publish_to: none

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  http_parser: ^4.0.2
  nayef_common_domain_toolkit:
    git:
      url: https://github.com/nayefradwi/nayef_flutter_dart_commons
      path: packages/nayef_common_domain_toolkit
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


