name: nayef_common_widgets
description: "A commons widgets for Nayef's projects. This package has simple widgets that are just built"
version: 0.0.1

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

